### ISSUE TITLE
stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by Sinderella** [nccgroup/dirble#1]
I quickly tested dirble and I came across this error message.

```
$ ./dirble http://127.0.0.1:8000 -w ~/clones/SecLists/Discovery/Web-Content/big.txt
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It seems like this line causes it. Removing the line fixed the error.

https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/big.txt#L16072

**Comment by Isona** [comment]
Thanks for the issue, it should be fixed on master now, and will be in a release in the next few days.
