### ISSUE TITLE
%ext% support

### ISSUE THREAD

**Issue by theblackturtle** [nccgroup/dirble#41]
Hi, I see dirble is not supporting `%ext%`/`%EXT%`. Many wordlists using this format and replace it with extensions.
Ex: admin.%ext% -> admin.php / admin.asp / admin.jsp

**Comment by uBadRequest** [comment]
I am seeing same problem.

**Comment by Isona** [comment]
Hi, thanks for the issue and apologies for the delay in replying, I'll look at adding it shortly!

**Comment by Isona** [comment]
This should now be implemented on the latest branch, you can use the --sub-ext flag to enable the substitution.

**Comment by theblackturtle** [comment]
I think It should use `lower("%EXT%"` because Many wordlists use both `%EXT%` and `%ext%`.
