### ISSUE TITLE
rename --host to --url

### ISSUE THREAD

**Issue by blshkv** [nccgroup/dirble#9]
I'm playing with the tool and getting confused everytime I run it.

```host``` is an IP address or a dns name. But what you really require is an URL (with scheme)
https://danielmiessler.com/study/url-uri/

**Comment by Isona** [comment]
Thanks for this, the short name was already -u for this reason but I had neglected to correct the long argument from earlier versions, it now correctly uses --uri and --url. I've released a new version 1.3.1 with this change in too.
